services:
  - type: web
    name: lost-and-found
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false